[package]
name = "rust-book-chapter-8"
version = "0.1.0"
authors = ["Alvaro Garcia <alvarogarcia7@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
